spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/greetings
        greetings-out:
          destination: greetings
#          contentType: application/greetings
format: YYYY-MM-dd HH:mm:ss
fixedDelay: 1000
